services:
  web:
    build: .
    command: sh -c "chmod +x /app/startup.sh && /app/startup.sh"
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - media_files:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static_files:
  media_files: