services:
  web:
    build: .
    command: sh -c "chmod +x /app/startup.sh && /app/startup.sh"
    volumes:
      - .:/app
      - static_files:/app/staticfiles
      - media_files:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
  celery:
    build: .
    command: uv run celery -A core.infrastructure.celery.app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
volumes:
  static_files:
  media_files: