from typing import Any, Protocol

from app.domain.users.entities import User


class IUserRepository(Protocol):
    def create(self, user: User) -> User: ...

    def update(self, user: User, **kwargs) -> User: ...

    def get_by_id(self, user_id: int) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def create_social_user(self, user: User) -> Any: ...

    def get_or_create_social_user(self, request: Any) -> User: ...
